### PR TITLE
Fix installation

### PR DESCRIPTION
**Pull request by tersmitten**

### CODE REVIEW

**Comment by tersmitten** [comment]
@mvdriel Still not working :-(

```
TASK [grafana : repository | add] ************************************************************************************
failed: [example.com] (item={'type': 'deb [arch=amd64]', 'url': 'https://apt.grafana.com stable', 'component': 'main'}) => {"ansible_loop_var": "item", "changed": false, "item": {"component": "main", "type": "deb [arch=amd64]", "url": "https://apt.grafana.com stable"}, "msg": "Failed to update apt cache: W:GPG error: https://apt.grafana.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 963FA27710458545, E:The repository 'https://apt.grafana.com stable InRelease' is not signed."}
```

**Comment by mvdriel** [comment]
@tersmitten I will have a look at it

**Comment by mvdriel** [comment]
@tersmitten It was revoked last week again. 😀 See: https://grafana.com/blog/2023/08/24/grafana-security-update-gpg-signing-key-rotation/ I will make a fix

**Comment by tersmitten** [comment]
They do that too often ...

**Comment by mvdriel** [comment]
@tersmitten Fix is in #7

**Pull request merged**
