### PR TITLE
Fix installation

### PR DESCRIPTION
**Pull request by mvdriel**

### CODE REVIEW

**Comment by tersmitten** [comment]
This is not working (not even for `20.04`, see #6); signing issue. Can you have a look? Maybe you can find something useful in #4.

**Comment by mvdriel** [comment]
@tersmitten not sure what I did, but it should work now. I prefer this way instead of adding the key manually. Do you agree?

**Comment by tersmitten** [comment]
Yes, I also prefer this way (as long as it works :-))

**Comment by tersmitten** [comment]
Seems to work now (at least in the vagrant)

**Comment by tersmitten** [comment]
fixed in #6

**Pull request closed without merging**
